set -g prefix C-a
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g mouse on

set -g status-interval 5
set -g status-position bottom
#set -g status-justify absolute-centre
set -g status-justify centre
set -g status-style "bg=default"

# left status
set -g status-left-length 35
set -g status-left "#[fg=#ff5189] #[fg=#e3c78a]#S #[default]"

# window status (centre)
set-window-option -g window-status-separator ''

set -g window-status-current-style "bg=#ae81ff, fg=#000000, bold"
set -g window-status-style "bg=#323437 fg=#c6c6c6"

set -g window-status-format " #I: #W "
set -g window-status-current-format " #I: #W "

# right status
#set -g status-right "#[fg=#e4e4e4] #(uptime | cut -f 4-5 -d ' ' | cut -f 1 -d ',')"
set -g status-right '#[fg=#3e8fb0]#{cpu_icon} #[fg=#c6c6c6]#{cpu_percentage}  #[fg=#3e8fb0]#{ram_icon} #[fg=#c6c6c6]#{ram_percentage}  #[fg=#c4a7e7] #[fg=#e3c78a]#(hostname)'

set -g pane-active-border-style "bg=default,fg=#89b4fa"
set -g pane-border-style "bg=default,fg=#313244"

# binds
unbind C-b
bind r source-file ~/.tmux.conf

unbind '"'
unbind %
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

#bind -r j resize-pane -D 5
#bind -r k resize-pane -U 5
#bind -r l resize-pane -R 5
#bind -r h resize-pane -L 5

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'


set -g @cpu_low_icon ""
set -g @cpu_medium_icon ""
set -g @cpu_high_icon ""

set -g @ram_low_icon "" # icon when cpu is low
set -g @ram_medium_icon "" # icon when cpu is medium
set -g @ram_high_icon "" # icon when cpu is high

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

