#!/usr/bin/env bash

sudo yabai --load-sa


yabai -m config                                 \
    external_bar all:32:0                       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                float             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_quint  \
    window_opacity_duration      0.2            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.9           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0             \
    bottom_padding               0             \
    left_padding                 0             \
    right_padding                0             \
    window_gap                   0             \
    layout                       bsp            \
    mouse_modifier               alt             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# -- spaces --
yabai -m space 1 --label desk1
yabai -m space 2 --label desk2
yabai -m space 3 --label desk3
yabai -m space 4 --label desk4
yabai -m space 5 --label desk5
yabai -m space 6 --label desk6
yabai -m space 7 --label desk7
yabai -m space 8 --label desk8
yabai -m space 9 --label desk9

#yabai -m rule --add app="^Ghostty$"           space=desk1
#yabai -m signal --add event=window_created app="Ghostty" action="yabai -m space --focus 1"

yabai -m rule --add app="^Brave Browser$"     space=desk2
yabai -m signal --add event=window_created app="Brave Browser" action="yabai -m space --focus 2"

yabai -m rule --add app="^kitty$"             space=desk1
yabai -m signal --add event=window_created app="kitty" action="yabai -m space --focus 1"

# float system preferences
yabai -m rule --add app="^Системные настройки$" manage=off

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
