font=Hack Nerd Font Mono:size=18
pad=5x0 center

[cursor]
style=block
blink=yes
blink-rate=500
beam-thickness=1.5
# underline-thickness=<font underline thickness>

# rose pine
#[colors-dark]
#alpha=0.8
#cursor=191724 e0def4 
##background=191724 
#background=000000 
#foreground=e0def4 
#
#regular0=26233a     # black (Overlay)
#regular1=eb6f92     # red (Love)
#regular2=9ccfd8     # green (Foam)
#regular3=f6c177     # yellow (Gold)
#regular4=31748f     # blue (Pine)
#regular5=c4a7e7     # magenta (Iris)
#regular6=ebbcba     # cyan (Rose)
#regular7=e0def4     # white (Text)
#
#bright0=47435d      # bright black (lighter Overlay)
#bright1=ff98ba      # bright red (lighter Love)
#bright2=c5f9ff      # bright green (lighter Foam)
#bright3=ffeb9e      # bright yellow (lighter Gold)
#bright4=5b9ab7      # bright blue (lighter Pine)
#bright5=eed0ff      # bright magenta (lighter Iris)
#bright6=ffe5e3      # bright cyan (lighter Rose)
#bright7=fefcff      # bright white (lighter Text)
#
#flash=f6c177        # yellow (Gold)
#
#vague
[colors-dark]
alpha=0.8
background=000000 
#background=141415
foreground=cdcdcd

regular0=252530
regular1=d8647e
regular2=7fa563
regular3=f3be7c
regular4=6e94b2
regular5=bb9dbd
regular6=aeaed1
regular7=cdcdcd

bright0=606079
bright1=e08398
bright2=99b782
bright3=f5cb96
bright4=8ba9c1
bright5=c9b1ca
bright6=bebeda
bright7=d7d7d7

flash=f3be7c



